### ISSUE TITLE
Objects are not valid as react child

### ISSUE THREAD

**Issue by Angelk90** [cesardeazevedo/react-native-bottom-sheet-behavior#29] opened 2017-08-19 05:46 UTC
Just compile app, from this error.
![screenshot_20170819-073400 1](https://user-images.githubusercontent.com/20476002/29483881-5ba36198-84b2-11e7-8cd8-1956ddc894a3.jpg)

**Comment by cesardeazevedo** [comment] 2017-08-19 20:35
Sorry, i don't know how to reproduce it, are you sure that is related to this project?

**Comment by Angelk90** [comment] 2017-08-19 22:17
I downloaded the example file:
https://github.com/cesardeazevedo/react-native-bottom-sheet-behavior/tree/master/example

Dependencies installed:
```
{
  "name": "example",
  "version": "0.0.2",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "android": "trash node_modules/react-native-bottom-sheet-behavior && npm install && react-native run-android",
    "lint": "eslint -c .eslintrc.js views index.android.js",
    "lint:fix": "eslint -c .eslintrc.js views index.android.js --fix"
  },
  "dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "^0.47.1",
    "react-native-bottom-sheet-behavior": "1.0.0-beta.7",
    "react-native-collapsing-toolbar": "^1.0.0-beta.5",
    "react-native-maps": "^0.10.0",
    "react-native-nested-scroll-view": "3.0.0",
    "react-native-vector-icons": "^4.3.0",
    "react-navigation": "1.0.0-beta.10"
  },
  "devDependencies": {
    "babel-preset-react-native": "^1.9.0",
    "eslint": "^3.9.1",
    "eslint-config-airbnb": "13.0.0",
    "eslint-plugin-babel": "^3.3.0",
    "eslint-plugin-import": "^2.1.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.6.0",
    "eslint-plugin-react-native": "2.1.0"
  }
}
```

Just start the project from the following error.

Is there any other way to test the module?

**Comment by Angelk90** [comment] 2017-08-20 04:35
@cesardeazevedo: The problem with that error message is the following line:
https://github.com/cesardeazevedo/react-native-bottom-sheet-behavior/blob/master/example/DrawerMenu.js#L117

That is: `{this.props.children}`
It's printed on consoles, something like this:
![error](https://user-images.githubusercontent.com/20476002/29492055-bc949cde-856f-11e7-8df7-c15fe8472b71.png)

What exactly is this {this.props.children} accurate?
As soon as I take the line, I get a white screen where DrawerLayoutAndroid works.

But when you click on one of the following items:
Simple, nestedScroll ....

I get the following error message:
Undefined is not an object (evaluating '_this.navigation.dispath')

She also said: Can not read property 'dispatch' of undefined.

Then go to the following line: https://github.com/cesardeazevedo/react-native-bottom-sheet-behavior/blob/master/example/index.android.js#L23
In: `handlePush = (routeName) => {`
I did print, `console.log(this.navigation)`, waiting for something to come back to me.
Print undefined.

I've also changed dependencies by updating some of them:
```
{
  "name": "example",
  "version": "0.0.2",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "android": "trash node_modules/react-native-bottom-sheet-behavior && npm install && react-native run-android",
    "lint": "eslint -c .eslintrc.js views index.android.js",
    "lint:fix": "eslint -c .eslintrc.js views index.android.js --fix"
  },
  "dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "^0.47.1",
    "react-native-bottom-sheet-behavior": "1.0.0-beta.7",
    "react-native-maps": "^0.16.2",
    "react-native-nested-scroll-view": "3.0.0",
    "react-native-vector-icons": "^4.3.0",
    "react-navigation": "^1.0.0-beta.11"
  },
  "devDependencies": {
    "babel-preset-react-native": "^1.9.0",
    "eslint": "^4.5.0",
    "eslint-config-airbnb": "15.1.0",
    "eslint-plugin-babel": "^4.1.2",
    "eslint-plugin-import": "^2.1.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-react": "^7.2.1",
    "eslint-plugin-react-native": "3.0.1"
  }
}
```


Some advice?

I do not know where I'm wrong, the only thing I did was take your example is installing dependencies and making the linking.

**Comment by cesardeazevedo** [comment] 2017-08-20 20:19
It's because you changed the `react-navigation` version, that has some breaking changes now, if you want to change it to use in your project is fine, but i've no intent to maintain the example, because it's actually poor written by myself, and just for people who want to give a quick test, nothing more.

I am currently in a vacation, so, i've no plans to update the example dependencies anytime soon, i would love to receive a pull request with these fixes.

**Comment by cesardeazevedo** [comment] 2017-11-19 17:40
`react-navigation` was updated to version `1.0.0-beta.13` at 1ab9403a0a4dbf5075ef2197a10c08d20bbceb3a, so i'm going to close this issue.

**Closed as completed by cesardeazevedo** 2017-11-19 17:40 UTC
